.\"-
.\" Copyright (c) 2016 The University of Oslo
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd September 14, 2016
.Dt FLYTRAP 8
.Os
.Sh NAME
.Nm flytrap
.Nd Detect and impede port scanners
.Sh SYNOPSIS
.Nm
.Op Fl dfnv
.Op Fl l Ar logfile
.Op Fl p Ar pidfile
.Op Fl x Ar address
.Fl i Ar interface
.Pp
.Nm
.Fl V
.Sh DESCRIPTION
The
.Nm
daemon attempts to detect port scanners and, if possible, slow them
down by forging responses to keep them occupied.
.Pp
The following options are available:
.Bl -tag -width Fl
.It Fl d
Enable log messages at debug level or higher.
.It Fl f
Foreground mode: do not daemonize and do not create a pidfile.
.It Fl n
Dry-run mode.
Does everything except inject packets into the network.
.It Fl i Ar interface
Listen on the specified interface.
.It Fl l Ar logfile
Log information about received packets in CSV format to the specified
file instead of
.Va stdout .
.It Fl p Ar pidfile
Write the daemon's PID to the specified file instead of
.Pa /var/run/flytrap.pid .
.It Fl v
Enable log messages at verbose level or higher.
.It Fl x Ar address
Whitelist the specified IP address.
This prevents
.Nm
from ever claiming it, even if it sees repeated unanswered ARP
requests for it.
This may be required on platforms where
.Xr pcap 3
does not capture outgoing traffic, as
.Nm
will see incoming ARP requests for its host's IP addresses, but not
the replies.
.El
If the 
.Sh SEE ALSO
.Xr pcap 3 ,
.Xr arp 8 ,
.Xr tcpdump 8
.Sh AUTHORS
The
.Nm
daemon and this manual page were written by
.An Dag-Erling Sm\(/orgrav Aq Mt d.e.smorgrav@usit.uio.no
for the University of Oslo.
